### ISSUE TITLE
你好，我是锤子科技的UI设计人员，你的这个开源项目涉嫌侵犯...

### ISSUE THREAD

**Issue by hackware1993** [hougr/SmartisanPull#3]
额，逗你玩呢，前段时间也想做一个这个，一直懒得写。其实你可以基于别的下拉刷新框架，比如UltraPullToRefresh，写一个自定义的header即可。

**Comment by hougr6** [comment]
哥们儿，你这标题吓我一跳啊，哈哈。我已经私信了锤子科技客服，询问是否侵权，还没有回复我。你说的UltraPullToRefresh一开始我也考虑了，但是还是想自己把下拉的逻辑也实现一下。考虑到这么多人喜欢（完全意料之外，本来设想30个star就OK了），我也觉得有必要基于UltraPullToRefresh实现一下了。你的MagicIndicator很不错，有空学习下

**Comment by hackware1993** [comment]
@hougr 要写好一个通用下拉刷新框架其实要处理的细节是很多的，在你的框架还未稳定之前，谁也不愿意冒着风险在项目中使用，且替换框架的成本可能非常大，但如果针对常用下拉刷新框架都开发一个header，则风险和成本就会小得多。

**Comment by hougr6** [comment]
@hackware1993 你说得有道理，近期我会基于一个稳定的下拉刷新框架写一个header
